# Assignment 3 – Encoding Categorical Variables

## Objective
To convert categorical variables into numerical form using LabelEncoder and OneHotEncoder.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
data = pd.read_csv("../Assignment_1_Data_Analysis/Titanic-Dataset.csv")

In [3]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
data['Sex'].unique()

<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

In [5]:
le = LabelEncoder()

data['Sex'] = le.fit_transform(data['Sex'])

In [6]:
data[['Sex']].head()

   Sex
0    1
1    0
2    0
3    0
4    1

In [7]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'female': np.int64(0), 'male': np.int64(1)}

In [8]:
data['Embarked'].unique()

<ArrowStringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [9]:
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

In [10]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [11]:
embarked_encoded = ohe.fit_transform(data[['Embarked']])

In [12]:
embarked_df = pd.DataFrame(
    embarked_encoded,
    columns=ohe.get_feature_names_out(['Embarked'])
)

In [13]:
embarked_df.head()

   Embarked_C  Embarked_Q  Embarked_S
0         0.0         0.0         1.0
1         1.0         0.0         0.0
2         0.0         0.0         1.0
3         0.0         0.0         1.0
4         0.0         0.0         1.0

In [14]:
data = data.drop('Embarked', axis=1)

In [15]:
data = pd.concat([data, embarked_df], axis=1)

In [16]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,0.0,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,1.0,0.0,0.0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0,0.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,0.0,0.0,1.0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,0.0,0.0,1.0

In [17]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked_C     float64
Embarked_Q     float64
Embarked_S     float64
dtype: object

## Conclusion

Categorical variables in the Titanic dataset were converted into numerical form. LabelEncoder was used for the binary Sex variable, while OneHotEncoder was used for the categorical Embarked variable. The encoded dataset can now be used by machine learning algorithms that require numerical input.